### ISSUE TITLE
unable to install the DIS

### ISSUE THREAD

**Issue by youssef-haidar** [SkylineCommunications/SLC-C-DevOpsExercise1#77]
i am unable to install the DIS.

I have already installed the DataMinerIntegrationStudio17-2.45.1.8.vsix but is not opening 

kindly advice

**Comment by MichielOda** [comment]
Hi @youssef-haidar 

Sorry for the late reply. As this exercise is partially automated we didn't notice your issue.

Make sure your Visual Studio is up to date and running the latest version. DIS can be found under 'Extensions' in the menu bar of Visual Studio.

If you would still have issues, I would suggest to ask your question on [DataMiner Dojo](https://community.dataminer.services/questions/). This way we'll be able to help you out easier and quicker.

Best regards

**Comment by youssef-haidar** [comment]
thanks

**Comment by youssef-haidar** [comment]
Hi Michiel,

I am still facing the same issue and i have posted it on DataMiner Dojo.

Regards,

**Comment by MichielOda** [comment]
Hi @youssef-haidar 

As answered already on Dojo, DIS is not supported on Visual Studio for Mac. I'll close this issue as this has now been resolved.

Best regards
